### ISSUE TITLE
RQGIS3 not available for R version 3.6.2

### ISSUE THREAD

**Issue by rmarzocchi84** [jannes-m/RQGIS3#22]
It seems there is only RQGIS package for the new version of R

**Comment by rmarzocchi84** [comment]
Obviously It is possible to install from github:

```
install.packages("remotes")
remotes::install_github("jannes-m/RQGIS3")
```

**Comment by pat-s** [comment]
As you can see in the README, there is no CRAN release yet of RQGIS3.
