### ISSUE TITLE
Can't install RQGIS3 using the remotes library. This is what I get:

### ISSUE THREAD

**Issue by jcmartinmu** [jannes-m/RQGIS3#27]
Error: (converted from warning) package 'reticulate' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'RQGIS3'

Thank you for your help!

**Comment by pat-s** [comment]
Please do not post screenshots but only code snippets.

More information is needed to provide help here.

**Comment by jannes-m** [comment]
Pls use qgisprocess from now on, which is the successor of RQGIS3 (see also README).
